-- Datos demo opcionales para validar el panel antes de recibir tráfico real.
-- Ejecutar solo en proyecto de prueba o borrar después.

insert into public.analytics_events (
  event_type,
  path,
  title,
  referrer,
  visitor_id,
  session_id,
  fingerprint_key,
  consent_status,
  ip_hash,
  country_code,
  country_name,
  region_code,
  region_name,
  city,
  timezone,
  device_type,
  browser,
  os,
  metadata,
  created_at
)
values
  (
    'page_view',
    '/',
    'Fenix Fight System',
    null,
    'demo-vis-1',
    'demo-ses-1',
    'demo-vis-1',
    'accepted',
    'demo-hash-1',
    'MX',
    'México',
    'TAM',
    'Tamaulipas',
    'Nuevo Laredo',
    'America/Matamoros',
    'mobile',
    'Chrome',
    'Android',
    '{}',
    now() - interval '2 days'
  ),
  (
    'page_view',
    '/videos',
    'Videos Fenix',
    'https://www.instagram.com/',
    'demo-vis-2',
    'demo-ses-2',
    'demo-vis-2',
    'accepted',
    'demo-hash-2',
    'US',
    'Estados Unidos',
    'TX',
    'Texas',
    'Laredo',
    'America/Chicago',
    'desktop',
    'Safari',
    'macOS',
    '{}',
    now() - interval '1 day'
  ),
  (
    'contact_click',
    '/',
    'Fenix Fight System',
    null,
    'demo-vis-1',
    'demo-ses-1',
    'demo-vis-1',
    'accepted',
    'demo-hash-1',
    'MX',
    'México',
    'TAM',
    'Tamaulipas',
    'Nuevo Laredo',
    'America/Matamoros',
    'mobile',
    'Chrome',
    'Android',
    '{"channel":"whatsapp"}',
    now() - interval '1 day'
  );
